CREATE TABLE [transfer].[transfer](
    transferId BIGINT IDENTITY(1000,1) NOT NULL,
    transferTypeId BIGINT NOT NULL,
    acquirerCode varchar(50),
    transferIdAcquirer varchar(50),
    transferIdLedger varchar(50),
    transferIdIssuer varchar(50),
    transferIdMerchant varchar(50),
    transferDateTime DATETIME2 NOT NULL,
    localDateTime varchar(14),
    settlementDate date,
    channelId BIGINT NOT NULL,
    channelType varchar(50) NOT NULL,
    ordererId bigint,
    merchantId varchar(50),
    merchantInvoice varchar(50),
    merchantPort varchar(50),
    merchantType varchar(50),
    cardId bigint,
    sourceAccount VARCHAR(50),
    destinationAccount VARCHAR(50),
    expireTime datetime,
    expireCount int,
    reversed BIT NOT NULL,
    retryTime datetime,
    retryCount int,
    ledgerTxState smallint,
    issuerTxState smallint,
    acquirerTxState smallint,
    merchantTxState smallint,
    issuerId varchar(50),
    ledgerId varchar(50),
    transferCurrency VARCHAR(3) NOT NULL,
    transferAmount MONEY NOT NULL,
    acquirerFee MONEY DEFAULT(0),
    issuerFee MONEY DEFAULT(0),
    transferFee MONEY DEFAULT(0),
    taxVAT MONEY DEFAULT(0),
    taxWTH MONEY DEFAULT(0),
    taxOther MONEY DEFAULT(0),
    commission MONEY DEFAULT(0),
    description VARCHAR(250),
    [comment] NVARCHAR(250),
    noteToSelf NVARCHAR(250),
    utilityRef NVARCHAR(250),
    transferIdT24 VARCHAR(50),
    sourceAccountWorkingBalance MONEY,
	sourceAccountOnlineBalance MONEY,
	sourceAccountLockedBalance MONEY,
    sourceAccountNewBalance MONEY,
    sourceAccountAccountCategory NVARCHAR(50),
	sourceAccountRiskProfile NVARCHAR(50),
    destinationAccountWorkingBalance MONEY,
	destinationAccountOnlineBalance MONEY,
	destinationAccountLockedBalance MONEY,
    destinationAccountNewBalance MONEY,
    destinationAccountAccountCategory NVARCHAR(50),
	destinationAccountRiskProfile NVARCHAR(50),
    transferStatusSuccess BIT DEFAULT(1),
    CONSTRAINT [pkTransferTransfer] PRIMARY KEY CLUSTERED ([transferId] ASC),
    CONSTRAINT [fkTransferTransfer_TransferType] FOREIGN KEY([transferTypeId]) REFERENCES [core].[itemName] ([itemNameId])
)