CREATE TABLE [transfer].[reverse](
    reverseId bigint IDENTITY(10,1) NOT NULL,
    transferId bigint NOT NULL,
    reverseAmount money NOT NULL,
    isPartial BIT null,
    issuerTxState smallint,
    issuerId varchar(50),
    transferDateTime datetime NOT NULL,
    localDateTime varchar(14),
    networkData varchar(20) NULL,
    issuerResponseCode varchar(10), 
    issuerResponseMessage varchar(250),
    originalRequest TEXT NULL,
    originalResponse TEXT NULL,
    stan char(6) NULL,
    createdBy BIGINT NULL,
    createdOn DATETIMEOFFSET (7), 
    updatedBy BIGINT NULL,
    updatedOn DATETIMEOFFSET (7),
    CONSTRAINT [pkTransferReverse] PRIMARY KEY CLUSTERED ([reverseId] ASC),
    CONSTRAINT [fkTransferReverse_Transfer] FOREIGN KEY([transferId]) REFERENCES [transfer].[transfer] ([transferId])
)