CREATE TABLE [transfer].[transfer](
    transferId bigint IDENTITY(1000,1) NOT NULL,
    transferTypeId bigint NOT NULL,
    acquirerCode varchar(50),
    transferIdAcquirer varchar(50),
    transferIdLedger varchar(50),
    transferIdIssuer varchar(50),
    transferIdMerchant varchar(50),
    transferDateTime datetime NOT NULL,
    localDateTime varchar(14),
    settlementDate date,
    channelId bigint NOT NULL,
    channelType varchar(50) NOT NULL,
    ordererId bigint,
    merchantId varchar(50),
    merchantInvoice varchar(50),
    merchantPort varchar(50),
    merchantType varchar(50),
    cardId bigint,
    sourceAccount varchar(50),
    destinationAccount varchar(50),
    expireTime datetime,
    expireCount int,
    reversed bit NOT NULL,
    retryTime datetime,
    retryCount int,
    ledgerTxState smallint,
    issuerTxState smallint,
    acquirerTxState smallint,
    merchantTxState smallint,
    issuerId varchar(50),
    ledgerId varchar(50),
    transferCurrency varchar(3) NOT NULL,
    transferAmount money NOT NULL,
    acquirerFee money DEFAULT(0),
    issuerFee money DEFAULT(0),
    transferFee money DEFAULT(0),
    taxVAT money DEFAULT(0),
    taxWTH money DEFAULT(0),
	taxOther money DEFAULT(0),
	commission money DEFAULT(0),
    description varchar(250),
    CONSTRAINT [pkTransferTransfer] PRIMARY KEY CLUSTERED ([transferId] ASC),
    CONSTRAINT [fkTransferTransfer_TransferType] FOREIGN KEY([transferTypeId]) REFERENCES [core].[itemName] ([itemNameId])
)