CREATE TABLE [transfer].[reverse](
    reverseId bigint IDENTITY(10,1) NOT NULL,
    transferId bigint NOT NULL,
    reverseAmount money NOT NULL,
    isPartial BIT null,
    issuerTxState smallint,
    issuerId varchar(50),
    issuerChannelId char(4) NULL,
    transferDateTime datetime2(0) NOT NULL,
    localDateTime varchar(14),
    networkData varchar(20) NULL,
    transferIdIssuer varchar(50),
    transferIdAcquirer varchar(50),
    issuerResponseCode varchar(10), 
    issuerResponseMessage varchar(250),
    originalRequest VARCHAR(MAX) NULL,
    originalResponse VARCHAR(MAX) NULL,
    stan char(6) NULL,
    requestSourceId char(6),
    createdBy BIGINT NULL,
    createdOn DATETIMEOFFSET (7), 
    updatedBy BIGINT NULL,
    updatedOn DATETIMEOFFSET (7),
    CONSTRAINT [pkTransferReverse] PRIMARY KEY CLUSTERED ([reverseId] ASC),
    CONSTRAINT [fkTransferReverse_Transfer] FOREIGN KEY([transferId]) REFERENCES [transfer].[transfer] ([transferId])
)