export const OPEN_REJECT_BATCH_POPUP = Symbol('OPEN_REJECT_BATCH_POPUP');
export const CLOSE_REJECT_BATCH_POPUP = Symbol('CLOSE_REJECT_BATCH_POPUP');
export const REJECT_BATCH = Symbol('REJECT_BATCH');
export const ADD_COMMENT_REJECT = Symbol('ADD_COMMENT_REJECT');
export const LOAD_BATCH_STATUSES_REJECT = Symbol('LOAD_BATCH_STATUSES_REJECT');
