export const OPEN_DISABLE_BATCH_POPUP = Symbol('OPEN_DISABLE_BATCH_POPUP');
export const CLOSE_DISABLE_BATCH_POPUP = Symbol('CLOSE_DISABLE_BATCH_POPUP');
export const DISABLE_BATCH = Symbol('DISABLE_BATCH');
export const ADD_COMMENT = Symbol('ADD_COMMENT');
export const LOAD_BATCH_STATUSES = Symbol('LOAD_BATCH_STATUSES');
