export const OPEN_DELETE_BATCH_POPUP = Symbol('OPEN_DELETE_BATCH_POPUP');
export const CLOSE_DELETE_BATCH_POPUP = Symbol('CLOSE_DELETE_BATCH_POPUP');
export const DELETE_BATCH = Symbol('DELETE_BATCH');
export const ADD_COMMENT = Symbol('ADD_COMMENT');
export const LOAD_BATCH_STATUSES_DELETE = Symbol('LOAD_BATCH_STATUSES_DELETE');
