export default {
    'TOGGLE': Symbol('TOGGLE_CARD_PRODUCT_TOOLBOX'),
    'SHOW_FILTERS': Symbol('SHOW_FILTERS_CARD_PRODUCT_TOOLBOX'),
    'SHOW_BUTTONS': Symbol('SHOW_BUTTONS_CARD_PRODUCT_TOOLBOX'),
    'TOGGLE_STATUS': Symbol('TOGGLE_STATUS_CARD_PRODUCT_TOOLBOX'),
    'PAYMENT_DISABLE': Symbol('PAYMENT_DISABLE'),
    'CHECK_PAYMENTS': Symbol('CHECK_PAYMENTS')
};
