export default {
    'TOGGLE': Symbol('TOGGLE_BATCH_PAYMENT'),
    'SHOW_FILTERS': Symbol('SHOW_FILTERS_BATCH_PAYMENT'),
    'SHOW_BUTTONS': Symbol('SHOW_BUTTONS_BATCH_PAYMENT'),
    'TOGGLE_STATUS': Symbol('TOGGLE_STATUS_BATCH_PAYMENT'),
    'CHECK_BATCH': Symbol('CHECK_BATCH'),
    'READY_BATCH': Symbol('READY_BATCH'),
    'GET_BATCH_DETAIL': Symbol('GET_BATCH_DETAIL')
};
