export const OPEN_PAY_BATCH_POPUP = Symbol('OPEN_PAY_BATCH_POPUP');
export const CLOSE_PAY_BATCH_POPUP = Symbol('CLOSE_PAY_BATCH_POPUP');
export const PAY_BATCH = Symbol('PAY_BATCH');
export const CHANGE_EXPIRATION_DATE = Symbol('CHANGE_EXPIRATION_DATE');
export const CHANGE_PAY_ACCOUNT = Symbol('CHANGE_PAY_ACCOUNT');
export const FETCH_PAY_ACCOUNTS = Symbol('FETCH_PAY_ACCOUNTS');
